import pyperclip
print('Убедитесь, что вы заранее скопировали текст')
print('--------------------------------------------')
s = pyperclip.paste()
s = s.replace('\n', ' ')
s = s.replace('\r', ' ')
n1 = len(s)
s = s.replace(' ', '')
n2 = len(s)
s = s.replace(',', '')
s = s.replace('.', '')
n3 = len(s)
print('Количество символов с пробелами: ' + str(n1))
print('Количество символов без пробелов: ' + str(n2))
print('Количество символов без знакoв препинания, без крапок и пробелов: ' + str(n3))
print('--------------------------------------------')
print(pyperclip.paste())